### ISSUE TITLE
Mod crashes the game when ending the day

### ISSUE THREAD

**Issue by NightFright2k19** [AlejandroAkbal/Stardew-Valley-Quick-Sell-Mod#2]
At least with SDV 1.5.6, it is impossible to use this mod since if you use it to send items to the shipping bin, the game crashes when you end the day, getting stuck in some sort of infinite loop.

**Comment by NightFright2k19** [comment]
Unfortunately still not fixed in v0.3.1.

**Comment by AlejandroAkbal** [comment]
Could you post the SMAPI log, please?

Alejandro Akbal
akbal.dev <https://akbal.dev>



9 ago 2022, 13:29 por ***@***.***:

**Comment by NightFright2k19** [comment]
[I had posted this log](https://smapi.io/log/ae849bf6588d46f980e0e82b91ae7509) in the SDV forums some days ago when I was trying v0.3.0, it's still the same.

Haven't tried latest v0.3.2 yet, though.

**Comment by NightFright2k19** [comment]
Update:
Version 0.3.2 does not seem to crash for me any more, at least not when using its hotkey right after starting a new day and ending it afterwards directly without doing anything else.

Will do a real stress test tomorrow to see if it's holding together under normal conditions.

**Comment by AlejandroAkbal** [comment]
Wonderful, thanks for your work!

I'll try to implement the GMCM setting for the hotkey.
If you know another mod that is open source and does this, please let me know.


Alejandro Akbal
akbal.dev <https://akbal.dev>



9 ago 2022, 19:23 por ***@***.***:

**Comment by NightFright2k19** [comment]
There are easier examples maybe, but I know that [Dynamic Reflections](https://github.com/Floogen/DynamicReflections) has a hotkey "R" to open its menu which is remappable via GMCM.

For translations, you can do it like I did in my [unofficial Wind Effects update](https://github.com/NightFright2k19/StardewMods/blob/master/WindEffects/ModEntry.cs).

Basically, instead of the actual text, you put this in your code:
`Helper.Translation.Get("translation.var")`

Then make a subdir called "i18n" and place a file called default.json inside, with code like:
```
{
   "translation.var": "englishtext1",
   "translation.var2": "englishtext2",
   [...]
}
```

**Comment by NightFright2k19** [comment]
Bad news:
After a more extensive test today, the crash happened again. I played until the end of the day, frequently using the sell function.

[I made a new SMAPI log](https://smapi.io/log/06aaa17758d44084973955d020c62144), but the error is the same as it has always been.

Maybe relevant:
I had a special order mission open which I was about to finish (gather and ship 100 pineapples). When I was testing yesterday, I didn't collect those pineapples, but today I did and shipped them, finishing the order. Maybe something is wrong with that as well (or in particular).

**Comment by AlejandroAkbal** [comment]
Thanks for reporting it, I will try to use a more "native" approach this time. Will get to it later.

Alejandro Akbal
akbal.dev <https://akbal.dev>



10 ago 2022, 10:43 por ***@***.***:

**Comment by AlejandroAkbal** [comment]
Please let me know if it is fixed this time u.u

**Comment by NightFright2k19** [comment]
For now, I have managed to survive two days in a row with the latest version and no crash happened. Not having to be afraid of losing the entire progress of an entire day is a good feeling! 

While this is definitely good news, I don't want to give my full seal of approval just yet. Let me still do at least one or two special orders and see how it goes.

**Comment by AlejandroAkbal** [comment]
I’ll be awaiting for your seal of approval, ps, check the settings

Alejandro Akbal
akbal.dev <https://akbal.dev>



11 ago 2022, 11:55 por ***@***.***:

**Comment by NightFright2k19** [comment]
I saw, you managed to get the keybind implemented. Excellent job! 
If you want help getting translation support added as well, I can help with that - it's not that hard (see my post above).

**Comment by NightFright2k19** [comment]
Update:
Made a pull request for the translation feature, including a German loca file since I am a native speaker. 

Still no crash after 4 ingame days btw, but so far I didn't get a new special order for mass shipping yet.

**Comment by AlejandroAkbal** [comment]
Wonderful, I'll merge and adjust it tomorrow!

Thank you for all your interest. ❤️

**Comment by NightFright2k19** [comment]
I will still keep testing. It cannot hurt to be 100% sure. Now hoping for favorable RNG to get one of these pineapple shipping missions again.
